### ISSUE TITLE
getAFreeTime()

### ISSUE THREAD

**Issue by anyayunli** [havefuncoding/free-code-camp#20]
Implement function getAFreeTime() to return the free time period you would like to spend with me and Kanika in late March, should be a valid time, null is not accepted. 😄   e.g. 26th March.

BTW, excellent job in this repo. 👍

**Comment by bobame** [comment]
Thanks @AranyaLi you guys are the best!! 😍  

```
function getAFreeTime(friends, date) {
  var awesomeFriends = friends.every(function(friend){
    return friend == awesome;
  });
  if (awesomeFriends && date == free) {
    return date;
  } 
}

getAFreeTime([Yun, Kanika], "26th March");
=> "26th March"
```

Can't wait! ❤️ ❤️

**Comment by anyayunli** [comment]
💯  ❤️ ❤️

**Comment by kanika-agrawal-87** [comment]
Love it!! 👍

**Comment by bobame** [comment]
💞 💞  🎉

**Comment by anyayunli** [comment]
updates: https://cl.ison24.com/#/sn/rv?id=1706600301&ph=4083689992

**Comment by bobame** [comment]
Best present ever ❤️, tracking here, https://github.com/havefuncoding/egghead-io :bowing_woman: 👍
